apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pgxedwk46-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/pgxedwk46-java-quarkus-gitops